import { Manrope } from "next/font/google";
import "./globals.css";

const font = Manrope({ 
  weight: ['400', '500', '700', '800'],
  style: ['normal'],
  subsets: ['latin']});

export const metadata = {
  title: "HealthCare Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={font.className} >
        {children}
      </body>
    </html>
  );
}
